Fixed text files parsing
face-hh/griddycode pull request #136
Opened 2024-05-13 21:13 UTC by SweetyAngel

Just a check if a file is text

2024-06-16 14:33 UTC, RealPacket requested changes
I think that it would be better if we merged #111 (disclaimer: my PR) because it actually fixes the core issue.
In this case, the core issue is that GriddyCode doesn't clear language data (syntax, IDE comments (my PR requires you to open the menu twice, probably will fix it later), etc.)

2024-06-16 14:33 UTC, RealPacket commented on Scripts/lua_singleton.gd
> +		editor.warn("[color=yellow]WARNING[/color]: File has no extension.\nGriddyCode can't recognize it's language.\nFile will be parsed as raw text.")
```suggestion
		editor.warn("[color=yellow]WARNING[/color]: File is plain text.\nGriddyCode can't recognize its language.\nFile will be parsed as raw text.")
```

2024-06-16 14:33 UTC, RealPacket commented on Scripts/lua_singleton.gd
> +		return
```suggestion
	if extension == "txt" :
		editor.warn("[color=yellow]WARNING[/color]: File is text file, not code.")
		return
```

There's literally only 1 extension in text_extensions. Why do we need an array right now?

2024-06-17 18:25 UTC, SweetyAngel commented
I will close this PR because I agree that your PR need to be merged

2024-06-17 18:25 UTC, closed without merging

2024-09-16 21:24 UTC, Real-Packet commented
GitHub decided to suspend my account, I think I have the source code for the PR somewhere on my other disk