Create css.lua
face-hh/griddycode pull request #94
Opened 2024-03-27 15:12 UTC by elefantapan

Idk if it can get better without modifying Godot source code

( I don't have time for it )

yall can do it without me then

2024-03-28 19:55 UTC, QuinceTart10 commented
Nice work, haven't tested it yet, but I see that you haven't added any comments.

2024-03-29 16:40 UTC, face-hh commented
@elefantapan could you please add the comments so I can merge this?

2024-04-04 12:47 UTC, RealPacket requested changes
Needs some cleanup
You'll need to add comments, as it will need
I'll try to add some comments *later*.
Also,
I never finished the last review which was supposed to fix the repetition,
that's why it took a long time

2024-05-06 06:51 UTC, ItsTato requested changes

2024-05-06 06:51 UTC, ItsTato commented on Lua/Plugins/css.lua
> +
```suggestion
highlight("}", "symbol")

```

2024-05-06 06:51 UTC, ItsTato commented on Lua/Plugins/css.lua
> +highlight("html", "reserved")
```suggestion

```

2024-05-06 06:51 UTC, ItsTato commented on Lua/Plugins/css.lua
> +highlight("head", "reserved")
```suggestion

```

2024-05-06 06:51 UTC, ItsTato commented on Lua/Plugins/css.lua
> +highlight("script", "reserved")
```suggestion

```

2024-05-06 06:51 UTC, ItsTato commented on Lua/Plugins/css.lua
> +highlight("title", "reserved")
```suggestion

```

2024-05-06 06:51 UTC, ItsTato commented on Lua/Plugins/css.lua
> +highlight("meta", "reserved")
```suggestion

```

2024-05-09 17:09 UTC, merged